---
collections:
  - name: amazon.aws
    version: ">=5.0.0,<6.0.0"  # Version 5.x is the "Gold Standard" for Ansible 2.16
  - name: community.general
    version: ">=8.0.0,<9.0.0"  # 8.x is more compatible with 2.16 than 9.x
  - name: ansible.posix
    version: ">=1.5.4"
