---
- name: Scan Windows 2025 Security Options and Upload to S3
  hosts: all
  gather_facts: yes
  vars:
    s3_bucket: "oml-s3-automation-sandbox"
    s3_path: "cis-baseline-files"
    aws_region: "eu-west-1"
    template_path: "{{ playbook_dir }}/../templates/baseline-local Policy-Security Options_report.j2"

    # Mapping registry keys to the friendly names from your screenshot
    security_options_map:
      "LSAAnonymousNameLookup": "Network access: Allow anonymous SID/Name translation"
      "MACHINE\\Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\System\\EnableLUA": "User Account Control: Run all administrators in Admin Approval Mode"
      "MACHINE\\Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\System\\FilterAdministratorToken": "User Account Control: Admin Approval Mode for the Built-in Administrator account"
      "MACHINE\\Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\System\\DontDisplayLastUserName": "Interactive logon: Do not display last user name"
      "MACHINE\\Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\System\\InactivityTimeoutSecs": "Interactive logon: Machine inactivity limit"
      "MACHINE\\System\\CurrentControlSet\\Control\\Lsa\\LimitBlankPasswordUse": "Accounts: Limit local account use of blank passwords to console logon only"
      "MACHINE\\System\\CurrentControlSet\\Control\\Lsa\\RestrictAnonymous": "Network access: Do not allow anonymous enumeration of SAM accounts"
      "MACHINE\\System\\CurrentControlSet\\Control\\Lsa\\EveryoneIncludesAnonymous": "Network access: Let Everyone permissions apply to anonymous users"
      "MACHINE\\System\\CurrentControlSet\\Control\\Lsa\\ForceGuest": "Network access: Sharing and security model for local accounts"
      "MACHINE\\System\\CurrentControlSet\\Services\\LanmanServer\\Parameters\\AutoShareServer": "Network access: Restrict clients allowed to make remote calls to SAM"
      # ... Additional 90+ settings will follow this same pattern
      "MACHINE\\System\\CurrentControlSet\\Control\\Session Manager\\Kernel\\ObCaseInsensitive": "System objects: Case-insensitive for non-Windows subsystems"
      "MACHINE\\System\\CurrentControlSet\\Control\\Session Manager\\ProtectionMode": "System objects: Strengthen default permissions of internal system objects"

  tasks:
    - name: Export Security Options Policy
      ansible.windows.win_shell: |
        $configFile = "C:\temp\security_options.inf"
        secedit /export /areas SECURITYPOLICY /cfg $configFile | Out-Null
        if (Test-Path $configFile) {
            # Filter for both registry values and LSA settings
            Get-Content $configFile | Where-Object { $_ -match '=' } | ForEach-Object {
                $parts = $_.ToString().Split('=')
                $key = $parts[0].Trim()
                $val = $parts[1].Trim()
                Write-Output "$key|$val"
            }
            Remove-Item $configFile
        }
      register: security_scan_raw

    - name: Ensure Local Report Directory Exists
      delegate_to: localhost
      ansible.builtin.file:
        path: "{{ playbook_dir }}/reports"
        state: directory

    - name: Generate Security Options HTML Report
      delegate_to: localhost
      ansible.builtin.template:
        src: "{{ template_path }}"
        dest: "{{ playbook_dir }}/reports/Security_Options_{{ inventory_hostname }}.html"

    - name: Upload to S3
      delegate_to: localhost
      amazon.aws.s3_object:
        bucket: "{{ s3_bucket }}"
        object: "{{ s3_path }}/Security_Options_{{ inventory_hostname }}_{{ ansible_date_time.iso8601_basic_short }}.html"
        src: "{{ playbook_dir }}/reports/Security_Options_{{ inventory_hostname }}.html"
        mode: put
        region: "{{ aws_region }}"
